version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: ad-analytics-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ad-analytics
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ad-analytics-network

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: ad-analytics-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - ad-analytics-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: ad-analytics-elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=AdAnalytics2024!Secure
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ad-analytics-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kibana (optional - for visualizing Elasticsearch data)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: ad-analytics-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=AdAnalytics2024!Secure
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - ad-analytics-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  ad-analytics-network:
    driver: bridge
